name: GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install pnpm
      run: pnpm install
