name: GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Install pnpm
        run: npm install -g pnpm

    - name: Install pnpm
        run: npm install -g pnpm
